apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-service
  namespace: adoption-system

spec:
  replicas: 2

  selector:
    matchLabels:
      app: dog-service

  template:
    metadata:
      labels:
        app: dog-service

    spec:
      containers:
        - name: dog-service
          image: ajgak/dog-service:2a90569ffdb921adb53090c52e9a424cf0735a19
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: APP_VERSION
              value: "1.0.0"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: DOG_DATABASE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 5
            failureThreshold: 12

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: dog-service
  namespace: adoption-system

spec:
  selector:
    app: dog-service

  ports:
    - port: 8081
      targetPort: 8081

  type: ClusterIP