apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: adoption-system
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/AjgaK/adoption-system-deployment.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: adoption-system

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true